"""add lease and lease_history tables

Revision ID: 27a23ceb8f2a
Revises: ddca2296df99
Create Date: 2026-03-20 10:01:18.707358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27a23ceb8f2a'
down_revision: Union[str, Sequence[str], None] = 'ddca2296df99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
