"""add permission, permission_history, fee_detail and unit_price tables

Revision ID: ddca2296df99
Revises: 844980e09609
Create Date: 2026-03-20 08:48:07.989231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ddca2296df99'
down_revision: Union[str, Sequence[str], None] = '844980e09609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('m_unit_price',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('property_type', sa.String(length=20), nullable=False),
    sa.Column('usage', sa.String(length=100), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('t_fee_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=False),
    sa.Column('case_type', sa.String(length=20), nullable=False),
    sa.Column('is_latest', sa.Boolean(), nullable=False),
    sa.Column('unit_price', sa.Integer(), nullable=False),
    sa.Column('area_sqm', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('months', sa.Integer(), nullable=False),
    sa.Column('fraction_days', sa.Integer(), nullable=False),
    sa.Column('base_amount', sa.Integer(), nullable=False),
    sa.Column('fraction_amount', sa.Integer(), nullable=False),
    sa.Column('subtotal', sa.Integer(), nullable=False),
    sa.Column('discount_rate', sa.Float(), nullable=False),
    sa.Column('discount_reason', sa.Text(), nullable=True),
    sa.Column('discounted_amount', sa.Integer(), nullable=False),
    sa.Column('tax_rate', sa.Float(), nullable=False),
    sa.Column('tax_amount', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Integer(), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('calculated_by', sa.Integer(), nullable=False),
    sa.Column('formula_version', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_fee_detail_case_id'), 't_fee_detail', ['case_id'], unique=False)
    op.create_table('t_permission_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_permission_history_target_id'), 't_permission_history', ['target_id'], unique=False)
    op.create_table('t_permission',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('permission_number', sa.String(length=20), nullable=True),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('parent_case_id', sa.Integer(), nullable=True),
    sa.Column('renewal_seq', sa.Integer(), nullable=False),
    sa.Column('is_latest_case', sa.Boolean(), nullable=False),
    sa.Column('applicant_name', sa.String(length=200), nullable=False),
    sa.Column('applicant_address', sa.String(length=300), nullable=False),
    sa.Column('purpose', sa.String(length=500), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('usage_area_sqm', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fee_amount', sa.Integer(), nullable=True),
    sa.Column('override_flag', sa.Boolean(), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('conditions', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('permission_date', sa.Date(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('delete_reason', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['parent_case_id'], ['t_permission.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['m_property.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_t_permission_parent_case_id'), 't_permission', ['parent_case_id'], unique=False)
    op.create_index(op.f('ix_t_permission_permission_number'), 't_permission', ['permission_number'], unique=True)
    op.create_index(op.f('ix_t_permission_property_id'), 't_permission', ['property_id'], unique=False)
    op.create_index(op.f('ix_t_permission_status'), 't_permission', ['status'], unique=False)
    op.drop_index(op.f('idx_audit_log_target'), table_name='t_audit_log')
    op.drop_index(op.f('idx_audit_log_target_time'), table_name='t_audit_log')
    op.drop_index(op.f('idx_audit_log_time'), table_name='t_audit_log')
    op.drop_index(op.f('idx_audit_log_user'), table_name='t_audit_log')
    op.drop_index(op.f('idx_file_related'), table_name='t_file')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_file_related'), 't_file', ['related_type', 'related_id'], unique=False)
    op.create_index(op.f('idx_audit_log_user'), 't_audit_log', ['user_id'], unique=False)
    op.create_index(op.f('idx_audit_log_time'), 't_audit_log', ['performed_at'], unique=False)
    op.create_index(op.f('idx_audit_log_target_time'), 't_audit_log', ['target_table', 'target_id', 'performed_at'], unique=False)
    op.create_index(op.f('idx_audit_log_target'), 't_audit_log', ['target_table', 'target_id'], unique=False)
    op.drop_index(op.f('ix_t_permission_status'), table_name='t_permission')
    op.drop_index(op.f('ix_t_permission_property_id'), table_name='t_permission')
    op.drop_index(op.f('ix_t_permission_permission_number'), table_name='t_permission')
    op.drop_index(op.f('ix_t_permission_parent_case_id'), table_name='t_permission')
    op.drop_table('t_permission')
    op.drop_index(op.f('ix_t_permission_history_target_id'), table_name='t_permission_history')
    op.drop_table('t_permission_history')
    op.drop_index(op.f('ix_t_fee_detail_case_id'), table_name='t_fee_detail')
    op.drop_table('t_fee_detail')
    op.drop_table('m_unit_price')
    # ### end Alembic commands ###
